= Hazelcast Guides UI
// Settings:
:experimental:
:hide-uri-scheme:
:guides-site-url: https://guides.hazelcast.org/home/
:antora-default-ui-url: https://gitlab.com/antora/antora-ui-default
:antora-url: https://antora.org/
:hazelcast-com: https://hazelcast.com/

The project customizes the {antora-default-ui-url}[default UI] of {antora-url}[Antora] project and produces the UI
used in the Hazelcast Guides {guides-site-url}[site].

See {antora-default-ui-url}[default UI] instructions - as both projects have the same structure,
to customize, preview and bundle the UI.

== Copyright and License

=== Software

The software content in the repository except for Hazelcast logo and icons, (build scripts, JavaScript files,
Handlebars templates, foundation CSS, utility icons, etc.) is the part of {antora-url}[Antora] project. As such,
use of the software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0]
(MPL-2.0).

=== Branding and Design

Copyright (C) 2020 {hazelcast-com}[Hazelcast, Inc]. All rights reserved.
