= Hazelcast Guides UI
// Settings:
:experimental:
:hide-uri-scheme:
:guides-site-url: https://guides.hazelcast.org/home/
:antora-default-ui-url: https://gitlab.com/antora/antora-ui-default
:antora-url: https://antora.org/
:hazelcast-com: https://hazelcast.com/
:guides-site-repo: https://github.com/hazelcast-guides/guides-site

The project customizes the {antora-default-ui-url}[default UI] of {antora-url}[Antora] project and produces the UI
used in the Hazelcast Guides {guides-site-url}[site]. The released bundles are fetched from antora-playbook.yml in
{guides-site-repo}[guides-site repository]:

[source,yml]
----
ui:
  bundle:
    url: https://github.com/hazelcast-guides/guides-ui/releases/download/v15/ui-bundle.zip
----

== Development

The source of the UI is placed under `src/`. During development phase, you can preview the
changes made in `src` with the content under `preview-src/`. After adding a custom content
to `preview-src/index.adoc`, also determine the page layout for your content. If no layout
is provided, the guide page layout (where the guide content is shown) will be used during
the preview. There are two layouts available: `landing` for the home page and the default
one for the content page:

[source]
----
:page-layout: landing
----

To see index.adoc rendered within the UI, run:

[source]
----
$ gulp preview
----

== Release

To create a new bundle, use `gulp`:

[source]
----
$ gulp bundle
----

This will create a zip file and it can be used for a new release.
The bundle url also must be updated in antora-playbook.yml.

== Copyright and License

=== Software

The software content in the repository except for Hazelcast logo and icons, (build scripts, JavaScript files,
Handlebars templates, foundation CSS, utility icons, etc.) is the part of {antora-url}[Antora] project. As such,
use of the software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0]
(MPL-2.0).

=== Branding and Design

Copyright (C) 2020 {hazelcast-com}[Hazelcast, Inc]. All rights reserved.
